name: 'Geeks for AI'
email: 'rahul.g2510@outlook.com'
description: ''
title: 'Geeks For AI'
baseurl: ''
disqus: 'geeksforaiç'
url: '/'
permalink: '/:title/'
google_analytics: UA—XXXXXXXX-X
theme: minima
plugins:
  - jekyll-feed
  - jekyll-watch
  - jekyll-seo-tag
  - jekyll-admin
jekyll_admin:
  hidden_links: null
authors:
  admin:
    name: Rahul Goel
    bio: >-
      Hi, I am Rahul, the Founder of Geeks for AI, you're currently previewing.
      I hope you like it!
    rahul:
      name:           Rahul Goel
      avatar:         /assets/images/avatar1.jpg
      bio:            "Hi, I am Rahul Goel, Founder of GeeksForAI, you're currently previewing. I hope you like it!"
      email:          rahul.g2510@outlook.com
      twitter:        https://twitter.com/wowthemesnet
# Syntax
markdown: kramdown
highlighter: rouge
# Paginate
paginate: 10